apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: exmple-role

rules:
  - apiGroups: ["*"]
    resources: ["*"] # services,pods,secrets,vb objeler
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exmple-rolebinding
  namespace: test
subjects:
  - kind: User
    name: juniorGroup
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: exmple-role
  apiGroup: rbac.authorization.k8s.io
